cd ../misp-taxonomies
gitchangelog >../misp-website/static/Changelog-misp-taxonomies.txt
cd ../misp-warninglists
gitchangelog >../misp-website/static/Changelog-misp-warninglists.txt
cd ../misp-objects
gitchangelog >../misp-website/static/Changelog-misp-objects.txt
cd ../misp-galaxy
gitchangelog >../misp-website/static/Changelog-misp-galaxy.txt
cd ../misp-modules
gitchangelog >../misp-website/static/Changelog-misp-modules.txt
cd ../PyMISP
gitchangelog >../misp-website/static/Changelog-PyMISP.txt
cd ../MISP
gitchangelog >../misp-website/static/Changelog.txt
cd ../misp-stix
gitchangelog >../misp-website/static/Changelog-misp-stix.txt
